metadata:
       "metadata.tsv" 
referenceFa:
        "/SAN/vyplab/HuRNASeq/minimap2/references/hg38"
referenceGTF:
        "/SAN/vyplab/HuRNASeq/GENCODE/gencode.v30.annotation.gtf"
inFolder:
        "fastq/"
outFolder:
        "processed/"
