data_code:
        "test"
metadata:
        #"/sc/arion/projects/als-omics/microglia_isoseq/microglia_isoseq_sample_metadata.xlsx"
        "/sc/arion/projects/als-omics/microglia_isoseq/test_isoseq_metadata.xlsx"
ref_genome:
        # omit the .fa
        "/sc/arion/projects/ad-omics/data/references/hg38_reference/hg38"
ref_gtf:
        # cannot be gzipped
        "/sc/arion/projects/ad-omics/data/references/hg38_reference/GENCODE/gencode.v30.annotation.gtf"
genome_code:
        "hg38"
gtf_code:
        "GENCODE_v30"
out_folder:
        "TALON/"


