data_code:
        "single_cell_isoseq_run_jun21"
metadata:
        "/sc/arion/projects/als-omics/microglia_isoseq/isoseq-pipeline/config-files/single_cell_metadata.tsv"
        #"/sc/arion/projects/als-omics/microglia_isoseq/test_isoseq_metadata.xlsx"
barcode_design:
       "T-12U-16B" 

ref_genome:
        # omit the .fa
        #"/sc/arion/projects/ad-omics/data/references/hg38_reference/hg38"
        "/sc/arion/projects/ad-omics/data/references/hg38_reference/GENCODE/gencode.v38.primary_assembly/GRCh38.primary_assembly.genome" 
ref_gtf:
        # cannot be gzipped
        "/sc/arion/projects/ad-omics/data/references/hg38_reference/GENCODE/gencode.v38.primary_assembly/gencode.v38.primary_assembly.annotation.gtf"
        #"/sc/arion/projects/ad-omics/data/references/hg38_reference/GENCODE/gencode.v30.annotation.gtf"
genome_code:
        "GRCh38_primary"
gtf_code:
        "GENCODE_v38"
out_folder:
        "results/single_cell/"


