fastqFolder:
        "fastq/"
dataCode:
        "hg19_minimap_default"
minimapParams:
        " -ax splice -uf -C5 "
metadata:
       "test_samples.tsv" 
referenceFa:
        # omit the .fa
        "reference/human_g1k_v37"
referenceGTF:
        "reference/gencode.v30lift37.annotation.gtf"
inFolder:
        "fastq/"
outFolder:
        "processed/"
